spring:
  application:
    name: safespace
  datasource:
    url: jdbc:postgresql://localhost:5432/ss-database
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    property-naming-strategy: SNAKE_CASE

security:
  jwt:
    secret-key:
    expiration-time: 604800000

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG

gemini:
  api-key:
cloudinary:
  cloud-name:
  api-key:
  api-secret: 